FINALPRO/FINALPRO/Controllers/ExcelController.cs
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FINALPRO.Controllers
{
    public class ExcelController : Controller
    {
        // GET: Excel
        public ActionResult Subida()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Subida(HttpPostedFileBase Subida)
        {
            if (ModelState.IsValid)
            {

                if (Subida != null && Subida.ContentLength > 0)
                {
                    // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                    // to get started. This is how we avoid dependencies on ACE or Interop:
                    Stream stream = Subida.InputStream;

                    // We return the interface, so that
                    IExcelDataReader reader = null;


                    if (Subida.FileName.EndsWith(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (Subida.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "El formato de este archivo no es compatible");
                        return View();
                    }

                    DataSet result = reader.AsDataSet(new ExcelDataSetConfiguration()
                    {
                        ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                        {
                            UseHeaderRow = true
                        }
                    });
                    reader.Close();

                    return View(result.Tables[0]);
                }
                else
                {
                    ModelState.AddModelError("File", "Porfavor cargue un archivo excel");
                }
            }
            return View();
        }
    }
}

FINALPRO/FINALPRO/Views/Excel/Subida.cshtml
@model System.Data.DataTable
@using System.Data;

<h2>Cargar y mostrar archivo excel</h2>

@using (Html.BeginForm("Subida", "Excel", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-group">
        <input  type="file" id="dataFile" name="Subida" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
    </div>

    <div class="form-group">
        <input type="submit" value="Cargar" class="btn btn-primary" />
    </div>

    if (Model != null)
    {
        <table>
            <thead>
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <th>@col.ColumnName</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
}