FINALPRO/FINALPRO/Controllers/ConvertidoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FINALPRO.Controllers
{
    public class ConvertidoresController : Controller
    {
        // GET: Convertidores
        public ActionResult Longitudes()
        {
            return View();
        }
        public ActionResult Temperatura()
        {
            return View();
        }
        public ActionResult Masa()
        {
            return View();
        }
        public ActionResult Datos()
        {
            return View();
        }
    }
}

FINALPRO/FINALPRO/Controllers/FiltroContenidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FINALPRO.Controllers
{
    public class FiltroContenidoController : Controller
    {
        // GET: FiltroContenido
        public ActionResult Musica()
        {
            return View();
        }
        public ActionResult Noticias()
        {
            return View();
        }
        public ActionResult AccionAventura()
        {
            return View();
        }
        public ActionResult Drama()
        {
            return View();
        }
        public ActionResult Infantiles()
        {
            return View();
        }
        public ActionResult Documentales()
        {
            return View();
        }
    }
}

FINALPRO/FINALPRO/Controllers/FormularioController.cs
using FINALPRO.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FINALPRO.Controllers
{
    public class FormularioController : Controller
    {
        // GET: Formulario
        public ActionResult Form()
        { 
            return View(); 
        }
        public ActionResult Mostrar(Formulario form, HttpPostedFileBase foto, HttpPostedFileBase Curriculum)
        {
            if (Curriculum.ContentLength > 0)
            {
                var fileName = Path.GetFileName(Curriculum.FileName);
                var path = Path.Combine(Server.MapPath("~/pdf"), fileName);
                Curriculum.SaveAs(path);
                ViewBag.curriculum = fileName;
            }
            if (foto.ContentLength > 0)
            {
                var fileName = Path.GetFileName(foto.FileName);
                var path = Path.Combine(Server.MapPath("~/img"), fileName);
                foto.SaveAs(path);
                ViewBag.foto = fileName;
            }
            return View(form);
        }
        public ActionResult Acerca()
        {
            return View();
        }
    }
}

FINALPRO/FINALPRO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu > .dropdown-menu {
                top: 0;
                left: 100%;
                margin-top: -6px;
                margin-left: 1px;
                -webkit-border-radius: 0 6px 6px 6px;
                -moz-border-radius: 0 6px 6px;
                border-radius: 0 6px 6px 6px;
            }

            .dropdown-submenu:hover > .dropdown-menu {
                display: block;
            }

            .dropdown-submenu > a:after {
                display: block;
                content: " ";
                float: right;
                width: 0;
                height: 0;
                border-color: transparent;
                border-style: solid;
                border-width: 5px 0 5px 5px;
                border-left-color: #ccc;
                margin-top: 5px;
                margin-right: -10px;
            }

            .dropdown-submenu:hover > a:after {
                border-left-color: #fff;
            }

            .dropdown-submenu.pull-left {
                float: none;
            }

                .dropdown-submenu.pull-left > .dropdown-menu {
                    left: 100%;
                    margin-left: 10px;
                    -webkit-border-radius: 6px 0 6px 6px;
                    -moz-border-radius: 6px 0 6px 6px;
                    border-radius: 6px 0 6px 6px;
                }

    </style>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Diversion", "form", "Formulario", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Formulario", "form", "Formulario")</li>
                    <li class="nav-item dropdown multi-level-dropdown">
                        <a href="#" id="menu" data-toggle="dropdown" class="nav-link dropdown-toggle w-100">Convertidores</a>
                        <ul class="dropdown-menu mt-2 rounded-0 primary-color border-0 z-depth-1">

                            <li class="nav-item dropdown">
                                @Html.ActionLink("Datos", "Datos", "Convertidores")
                            </li>
                            <li class="nav-item dropdown">
                                @Html.ActionLink("Longitudes", "Longitudes", "Convertidores")
                            </li>
                            <li class="nav-item dropdown">
                                @Html.ActionLink("Masa", "Masa", "Convertidores")
                            </li>
                            <li class="nav-item dropdown">
                                @Html.ActionLink("Temperatura", "Temperatura", "Convertidores")
                            </li>
                        </ul>
                        </li>
                            <li>@Html.ActionLink("Excel", "Subida", "Excel")</li>
                            <li class="nav-item dropdown multi-level-dropdown">
                                <a href="#" id="menu" data-toggle="dropdown" class="nav-link dropdown-toggle w-100">Filtro Contenido</a>
                                <ul class="dropdown-menu mt-2 rounded-0 primary-color border-0 z-depth-1">

                                    <li class="nav-item dropdown">
                                        @Html.ActionLink("Musica", "Musica", "FiltroContenido")
                                    </li>
                                    <li class="nav-item dropdown">
                                        @Html.ActionLink("Noticias", "Noticias", "FiltroContenido")
                                    </li>
                                    <li class="dropdown-item dropdown-submenu p-0">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle text-white w-100">Peliculas</a>
                                        <ul class="dropdown-menu ml-2 rounded-0 primary-color border-0 z-depth-1">
                                            <li class="dropdown-item p-0">
                                                @Html.ActionLink("Accion y Aventura", "AccionAventura", "FiltroContenido")
                                            </li>
                                            <li class="dropdown-item p-0">
                                                @Html.ActionLink("Drama", "Drama", "FiltroContenido")
                                            </li>
                                            <li class="dropdown-item p-0">
                                                @Html.ActionLink("Infantiles", "Infantiles", "FiltroContenido")
                                            </li>
                                            <li class="dropdown-item p-0">
                                                @Html.ActionLink("Documentales", "Documentales", "FiltroContenido")
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Acerca de", "Acerca", "Formulario")</li>
                        </ul>

                        @Html.Partial("_LoginPartial")
</div>
    </div>
</div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script>

    $('.multi-level-dropdown .dropdown-submenu > a').on("mouseenter", function (e) {
        var submenu = $(this);
        $('.multi-level-dropdown .dropdown-submenu .dropdown-menu').removeClass('show');
        submenu.next('.dropdown-menu').addClass('show');
        e.stopPropagation();
    });

    $('.multi-level-dropdown .dropdown').on("hidden.bs.dropdown", function () {
        // hide any open menus when parent closes
        $('.multi-level-dropdown .dropdown-menu.show').removeClass('show');
    });
</script>